### ISSUE TITLE
Use Y-Axis and Y-Scale

### ISSUE THREAD

**Issue by atago0129** [atago0129/roadmappy#13]
Now Y-Axis is drawn by original text box.
Then, it converts to use d3 Y-Axis, Y-Scale.

**Comment by atago0129** [comment]
[WIP]https://github.com/atago0129/roadmappy/commit/a160407926578176d07530151ec8ea7a05e958d5

**Comment by atago0129** [comment]
Render as ＊Bar Chart＊ for now.
But we must refactor a lot...

**Comment by atago0129** [comment]
Maybe, this contain a bug if task has multiple assignees and specify assignee type.

**Comment by hrsh7th** [comment]
We use y scale now.
