### ISSUE TITLE
webpack build time very long.

### ISSUE THREAD

**Issue by hrsh7th** [atago0129/roadmappy#6]
Because webpack.config.js's `babel-loader` section has not exclude option.

I tried adding exclude option, But it's not work.

Not working reason is `d3-v4-contextmenu` is not pre-compiled by babel.

We should re-publish compiled version `d3-v4-contextmenu`.

**Comment by atago0129** [comment]
thanks for your work
https://github.com/atago0129/d3-v4-contextmenu/pull/1
